#!/bin/bash
# ============================================================
# ZeroClaw SWAL Node - Termux Setup v4.2
# With interactive menu and SWAL status dashboard
# ============================================================

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

log() { printf "%b[SWAL]%b %s\n" "$1" "$NC" "$2"; }
info()    { log "$CYAN" "$@"; }
success() { log "$GREEN" "$@"; }
warn()    { log "$YELLOW" "$@"; }
error()   { log "$RED" "$@"; }

CONFIG_FILE="$HOME/.zeroclaw/config.toml"
STATUS_SCRIPT="$HOME/.local/bin/swal-status.sh"
STATUS_URL="https://raw.githubusercontent.com/iberi22/zeroclaw-termux-dev-setup/master/scripts/swal-status.sh"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}  ${BOLD}${GREEN}ZeroClaw SWAL Node - Termux Setup v4.2${NC}           ${CYAN}║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ============================================================
# 1. FIX BROKEN CONFIG
# ============================================================
info "1/5 - Verificando configuraciones rotas..."

if [[ -f "$HOME/.bashrc" ]]; then
    if grep -q "zeroclaw start" "$HOME/.bashrc" 2>/dev/null; then
        warn "Encontrado 'zeroclaw start' en .bashrc - removiendo..."
        sed -i '/zeroclaw start/d' "$HOME/.bashrc"
        success "Reparado .bashrc"
    fi
fi

if [[ -f "$HOME/.zshrc" ]]; then
    if grep -q "zeroclaw start" "$HOME/.zshrc" 2>/dev/null; then
        warn "Encontrado 'zeroclaw start' en .zshrc - removiendo..."
        sed -i '/zeroclaw start/d' "$HOME/.zshrc"
        success "Reparado .zshrc"
    fi
fi

success "Configuraciones rotas verificadas"

# ============================================================
# 2. CLEAN MOTD
# ============================================================
info "2/5 - Limpiando mensajes de inicio..."
touch "$HOME/.hushlogin" 2>/dev/null || true
success "Mensajes limpiados"

# ============================================================
# 3. INSTALL SWAL STATUS SCRIPT
# ============================================================
info "3/5 - Instalando SWAL status dashboard..."

mkdir -p "$HOME/.local/bin"

if command -v curl &>/dev/null; then
    if curl -fsSL "$STATUS_URL" -o "$STATUS_SCRIPT" 2>/dev/null; then
        chmod +x "$STATUS_SCRIPT" 2>/dev/null || true
        success "swal-status.sh instalado"
    else
        warn "No se pudo descargar swal-status.sh"
    fi
else
    warn "curl no disponible"
fi

# Add to MOTD
MOTD_LINE='[[ -x "$HOME/.local/bin/swal-status.sh" ]] && "$HOME/.local/bin/swal-status.sh"'

if [[ -f "$HOME/.bashrc" ]] && ! grep -q "swal-status.sh" "$HOME/.bashrc" 2>/dev/null; then
    echo "" >> "$HOME/.bashrc"
    echo "# SWAL Status Dashboard" >> "$HOME/.bashrc"
    echo "$MOTD_LINE" >> "$HOME/.bashrc"
fi

if [[ -f "$HOME/.zshrc" ]] && ! grep -q "swal-status.sh" "$HOME/.zshrc" 2>/dev/null; then
    echo "" >> "$HOME/.zshrc"
    echo "# SWAL Status Dashboard" >> "$HOME/.zshrc"
    echo "$MOTD_LINE" >> "$HOME/.zshrc"
fi

success "MOTD configurado"

# ============================================================
# 4. CONFIGURE ZEROCLAW
# ============================================================
info "4/5 - Configurando ZeroClaw..."

mkdir -p "$HOME/.zeroclaw"

cat > "$CONFIG_FILE" << 'CONFIGEOF'
# ZeroClaw Config - Generated by setup-termux.sh v4.2
# SWAL Node - SouthWest AI Labs

[agent]
autonomy_level = "full"

[security]
allowed_commands = ["pkg", "pkg_install", "pkg_update", "pkg_upgrade", "termux-setup-storage", "git", "curl", "wget", "bash", "sh", "echo", "pwd", "ls", "cd", "mkdir", "rm", "cp", "mv", "cat", "grep", "sed", "awk", "find", "npm", "node", "python", "python3", "pip", "pip3"]

[workspace]
path = "~/.zeroclaw/workspace"
CONFIGEOF

success "ZeroClaw configurado"

# ============================================================
# 5. SHOW CONFIG
# ============================================================
info "5/5 - Mostrando configuracion..."

echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  CONFIGURACION DE SEGURIDAD ZEROCLAW${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Archivo: $CONFIG_FILE"
echo ""
cat "$CONFIG_FILE"
echo ""

# Verify
if grep -q 'autonomy_level = "full"' "$CONFIG_FILE"; then
    success "autonomy_level = full OK"
else
    error "ERROR: autonomy_level no configurado!"
fi

if grep -q 'allowed_commands' "$CONFIG_FILE"; then
    success "allowed_commands OK"
else
    error "ERROR: allowed_commands no configurado!"
fi

# ============================================================
# SHOW STATUS DASHBOARD
# ============================================================
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  STATUS DEL SISTEMA${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if [[ -x "$STATUS_SCRIPT" ]]; then
    bash "$STATUS_SCRIPT"
else
    # Fallback inline status
    echo -e "${CYAN}--- Servicios ---${NC}"
    echo -n "  ZeroClaw: "
    if pgrep -f "zeroclaw daemon" &>/dev/null; then
        echo -e "${GREEN}✅ running${NC}"
    elif command -v zeroclaw &>/dev/null; then
        echo -e "${YELLOW}⚠️  stopped${NC}"
    else
        echo -e "${RED}❌ not installed${NC}"
    fi
fi

# ============================================================
# INTERACTIVE MENU
# ============================================================
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  MENU DE ACCIONES${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "   ${GREEN}[1]${NC}  Iniciar ZeroClaw daemon"
echo -e "   ${GREEN}[2]${NC}  Reiniciar ZeroClaw daemon"
echo -e "   ${GREEN}[3]${NC}  Ver status completo (swal-status)"
echo -e "   ${GREEN}[4]${NC}  Ver config de ZeroClaw"
echo -e "   ${GREEN}[5]${NC}  Abrir shell de ZeroClaw"
echo -e "   ${GREEN}[0]${NC}  Salir (solo mostrar MOTD)"
echo ""
echo -ne "   ${BOLD}Selecciona una opcion:${NC} "

read -r option

case "$option" in
    1)
        echo ""
        info "Iniciando ZeroClaw daemon..."
        if command -v zeroclaw &>/dev/null; then
            echo -e "${GREEN}Ejecutando: zeroclaw daemon${NC}"
            echo -e "${DIM}Usa Ctrl+C para detener${NC}"
            echo ""
            zeroclaw daemon
        else
            echo -e "${RED}zeroclaw no esta instalado${NC}"
        fi
        ;;
    2)
        echo ""
        info "Reiniciando ZeroClaw daemon..."
        pkill zeroclaw 2>/dev/null || true
        sleep 1
        if command -v zeroclaw &>/dev/null; then
            echo -e "${GREEN}Ejecutando: zeroclaw daemon${NC}"
            zeroclaw daemon
        else
            echo -e "${RED}zeroclaw no esta instalado${NC}"
        fi
        ;;
    3)
        echo ""
        if [[ -x "$STATUS_SCRIPT" ]]; then
            bash "$STATUS_SCRIPT"
        else
            echo -e "${RED}swal-status.sh no encontrado${NC}"
        fi
        ;;
    4)
        echo ""
        echo -e "${CYAN}--- Contenido de $CONFIG_FILE ---${NC}"
        cat "$CONFIG_FILE"
        ;;
    5)
        echo ""
        info "Abriendo shell de ZeroClaw..."
        if command -v zeroclaw &>/dev/null; then
            zeroclaw shell
        else
            echo -e "${RED}zeroclaw no esta instalado${NC}"
        fi
        ;;
    0|*)
        echo ""
        info "Saliendo..."
        echo ""
        echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${GREEN}  ✅ Setup completado!${NC}"
        echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        echo -e "  ${BOLD}Proximos pasos:${NC}"
        echo -e "    1. ZeroClaw ya esta configurado con autonomy=full"
        echo -e "    2. Cada vez que abras Termux veras el dashboard SWAL"
        echo -e "    3. Para ocultar MOTD: ${CYAN}touch ~/.swal-motd-disable${NC}"
        echo ""
        echo -e "  ${BOLD}Comandos utiles:${NC}"
        echo -e "    ${GREEN}zeroclaw daemon${NC}  - Iniciar daemon"
        echo -e "    ${GREEN}swal-status${NC}       - Ver status"
        echo -e "    ${GREEN}htop${NC}              - Monitor"
        echo ""
        ;;
esac