#!/bin/bash
# ============================================================
# ZeroClaw SWAL Node - Termux Setup v4.0 (MINIMAL)
# Minimal, fast, guaranteed to work
# ============================================================

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'

log() { printf "%b[SWAL]%b %s\n" "$1" "$NC" "$2"; }
info()    { log "$CYAN" "$@"; }
success() { log "$GREEN" "$@"; }
warn()    { log "$YELLOW" "$@"; }
error()   { log "$RED" "$@"; }

CONFIG_FILE="$HOME/.zeroclaw/config.toml"

echo ""
echo "============================================================"
echo "  ZeroClaw SWAL Node - Termux Setup v4.0"
echo "============================================================"
echo ""

# ============================================================
# 1. FIX BROKEN CONFIG (remove zeroclaw start if present)
# ============================================================
info "1/4 - Verificando configuraciones rotas..."

if [[ -f "$HOME/.bashrc" ]]; then
    if grep -q "zeroclaw start" "$HOME/.bashrc" 2>/dev/null; then
        warn "Encontrado 'zeroclaw start' en .bashrc - removiendo..."
        sed -i '/zeroclaw start/d' "$HOME/.bashrc"
        success "Reparado .bashrc"
    fi
fi

if [[ -f "$HOME/.zshrc" ]]; then
    if grep -q "zeroclaw start" "$HOME/.zshrc" 2>/dev/null; then
        warn "Encontrado 'zeroclaw start' en .zshrc - removiendo..."
        sed -i '/zeroclaw start/d' "$HOME/.zshrc"
        success "Reparado .zshrc"
    fi
fi

success "Configuraciones rotas verificadas"

# ============================================================
# 2. CLEAN MOTD
# ============================================================
info "2/4 - Limpiando mensajes de inicio..."
touch "$HOME/.hushlogin" 2>/dev/null || true
success "Mensajes limpiados"

# ============================================================
# 3. CONFIGURE ZEROCLAW
# ============================================================
info "3/4 - Configurando ZeroClaw..."

mkdir -p "$HOME/.zeroclaw"

# Write config file
cat > "$CONFIG_FILE" << 'CONFIGEOF'
# ZeroClaw Config - Generated by setup-termux.sh v4.0

[agent]
autonomy_level = "full"

[security]
allowed_commands = ["pkg", "pkg_install", "pkg_update", "pkg_upgrade", "termux-setup-storage", "git", "curl", "wget", "bash", "sh", "echo", "pwd", "ls", "cd", "mkdir", "rm", "cp", "mv", "cat", "grep", "sed", "awk", "find", "npm", "node", "python", "python3", "pip", "pip3"]

[workspace]
path = "~/.zeroclaw/workspace"
CONFIGEOF

success "ZeroClaw configurado"

# ============================================================
# 4. SHOW CONFIG
# ============================================================
info "4/4 - Mostrando configuracion..."

echo ""
echo "============================================================"
echo "  CONFIGURACION DE SEGURIDAD ZEROCLAW"
echo "============================================================"
echo ""
echo "Archivo: $CONFIG_FILE"
echo ""
cat "$CONFIG_FILE"
echo ""
echo "============================================================"

# Verify config was written correctly
if grep -q 'autonomy_level = "full"' "$CONFIG_FILE"; then
    success "autonomy_level = full OK"
else
    error "ERROR: autonomy_level no configurado!"
fi

if grep -q 'allowed_commands' "$CONFIG_FILE"; then
    success "allowed_commands OK"
else
    error "ERROR: allowed_commands no configurado!"
fi

echo ""
echo "============================================================"
echo "  SETUP COMPLETADO!"
echo "============================================================"
echo ""
info "Proximos pasos:"
echo "  1. Copia el config de arriba si necesitas compartirlo"
echo "  2. Inicia zeroclaw: zeroclaw daemon"
echo "  3. O reinicia si ya estaba corriendo: pkill zeroclaw; zeroclaw daemon"
echo ""
echo "Para verificar el bot funciona, envoyale un mensaje en Telegram"
echo "y debe responder sin pedir aprobacion."
echo ""